export enum Status {
  NEW = "NEW",
  ACTIVE = "ACTIVE",
  PENDING = "PENDING",
  INACTIVE = "INACTIVE",
  EXPIRED = "EXPIRED",
}

export enum ActiveInactiveStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  PENDING = "PENDING",
}

export enum AppointmentStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  NO_SHOW = "NO_SHOW",
  RESCHEDULED = "RESCHEDULED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum PaymentMethod {
  SSL_COMMERZ = "sslcommerz",
  BKASH = "bkash",
  NAGAD = "nagad",
  ROCKET = "rocket",
  CASH = "CASH",
}

export enum QueueStatus {
  WAITING = "WAITING",
  CALLED = "CALLED",
  IN_CONSULTATION = "IN_CONSULTATION",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
}

export enum PrescriptionStatus {
  PRESCRIBED = "PRESCRIBED",
  DISPENSED = "DISPENSED",
  PARTIALLY_GIVEN = "PARTIALLY_GIVEN",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum TestOrderStatus {
  ORDERED = "ORDERED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  SAMPLE_PENDING = "SAMPLE_PENDING",
  SAMPLE_COLLECTED = "SAMPLE_COLLECTED",
  PROCESSING = "PROCESSING",
  REPORT_READY = "REPORT_READY",
  APPROVED = "APPROVED",
  CANCELLED = "CANCELLED",
}

export enum AdmissionStatus {
  REQUESTED = "REQUESTED",
  ADMITTED = "ADMITTED",
  ON_TREATMENT = "ON_TREATMENT",
  READY_FOR_DISCHARGE = "READY_FOR_DISCHARGE",
  DISCHARGED = "DISCHARGED",
  CANCELLED = "CANCELLED",
}

export enum BedStatus {
  AVAILABLE = "AVAILABLE",
  RESERVED = "RESERVED",
  OCCUPIED = "OCCUPIED",
  MAINTENANCE = "MAINTENANCE",
}

export enum InvoiceStatus {
  DRAFT = "DRAFT",
  ISSUED = "ISSUED",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  PAID = "PAID",
  DUE = "DUE",
  CANCELLED = "CANCELLED",
  REFUNDED = "REFUNDED",
}

export enum CommissionType {
  PERCENTAGE = "PERCENTAGE",
  FIXED_AMOUNT = "FIXED_AMOUNT",
  NONE = "NONE",
}

export enum CommissionStatus {
  EARNED = "EARNED",
  PAYABLE = "PAYABLE",
  APPROVED = "APPROVED",
  SETTLED = "SETTLED",
  CANCELLED = "CANCELLED",
}

export enum ServiceCategory {
  CONSULTATION = "CONSULTATION",
  TEST = "TEST",
  ADMISSION = "ADMISSION",
  BED = "BED",
  OPERATION = "OPERATION",
  MEDICINE = "MEDICINE",
  MEDICAL_SUPPLY = "MEDICAL_SUPPLY",
  NURSING = "NURSING",
  MEAL = "MEAL",
  SERVICE = "SERVICE",
  OTHER = "OTHER",
}

export enum OperationStatus {
  PLANNED = "PLANNED",
  SCHEDULED = "SCHEDULED",
  ADMITTED = "ADMITTED",
  PRE_OP = "PRE_OP",
  READY_FOR_OT = "READY_FOR_OT",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  POST_OP = "POST_OP",
  CANCELLED = "CANCELLED",
}

export enum NursingTaskType {
  MEDICATION = "MEDICATION",
  INJECTION = "INJECTION",
  VITALS_CHECK = "VITALS_CHECK",
  WOUND_CARE = "WOUND_CARE",
  DRESSING = "DRESSING",
  PATIENT_OBSERVATION = "PATIENT_OBSERVATION",
  MEAL = "MEAL",
  TRANSFER = "TRANSFER",
  OTHER = "OTHER",
}

export enum NursingTaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
}

export enum MedicationAdminStatus {
  SCHEDULED = "SCHEDULED",
  GIVEN = "GIVEN",
  SKIPPED = "SKIPPED",
  REFUSED = "REFUSED",
}

export enum InventoryCategory {
  MEDICINE = "MEDICINE",
  INJECTION = "INJECTION",
  BANDAGE = "BANDAGE",
  SURGICAL_ITEM = "SURGICAL_ITEM",
  MEDICAL_SUPPLY = "MEDICAL_SUPPLY",
  EQUIPMENT = "EQUIPMENT",
  OTHER = "OTHER",
}

export enum StockTransactionType {
  PURCHASE = "PURCHASE",
  SALE = "SALE",
  ISSUE_TO_PATIENT = "ISSUE_TO_PATIENT",
  ISSUE_TO_OPERATION = "ISSUE_TO_OPERATION",
  ISSUE_TO_DEPARTMENT = "ISSUE_TO_DEPARTMENT",
  RETURN = "RETURN",
  ADJUSTMENT = "ADJUSTMENT",
  EXPIRED = "EXPIRED",
  DAMAGED = "DAMAGED",
}

export enum SupplySource {
  CLINIC_STOCK = "CLINIC_STOCK",
  EXTERNAL_PURCHASE = "EXTERNAL_PURCHASE",
  PATIENT_PROVIDED = "PATIENT_PROVIDED",
}

export enum SalaryType {
  MONTHLY = "MONTHLY",
  DAILY = "DAILY",
  PER_VISIT = "PER_VISIT",
  PER_OPERATION = "PER_OPERATION",
  COMMISSION_BASED = "COMMISSION_BASED",
  HOURLY = "HOURLY",
}

export enum PayrollStatus {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
}

