export const collectionsName = {
  user: "User",
  admin: "Admin",
  profile: "Profile",
  merchant: "Merchant",
  doctor: "Doctor",
  staff: "Staff",
  staffRoleTemplate: "StaffRoleTemplate",
  employee: "Employee",
  patient: "Patient",
  appointment: "Appointment",
  medicalRecord: "MedicalRecord",
  attendance: "Attendance",
  subscription: "Subscription",
  clinic: "Clinic",
  income: "Income",
  expense: "Expense",
  payment: "Payment",
  auditLog: "AuditLog",
  setting: "Setting",
  merchantPG: "MerchantPG",
  encounter: "Encounter",
  prescription: "Prescription",
  testCatalog: "TestCatalog",
  testOrder: "TestOrder",
  labReport: "LabReport",
};
